name: LinkedIn post automation

on: 
   schedule:
         - cron: '0 */2 * * *'
      
jobs:
  Testing_script:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v2
       
     - name: Setup python
       uses: actions/setup-python@v2
       with:
          python-version: 3.8
       
     - name: Execute script 
       env: 
             v1: a
             v2: b
             v3: c 
       run: |
          python t1.py $v1 $v2 $v3
          
